version: '3.8'

services:

  backend:
    build: ./backend
    container_name: ollama-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - ollama

  frontend:
    build: ./frontend
    container_name: ollama-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  ollama-data:
